#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU1                       100
#define IDD_DIALOG_ADD_PLAYER           106
#define IDC_CURSOR_LINE                 107
#define IDC_CURSOR_DOT                  108
#define IDC_CURSOR_DOT_CON              109
#define IDC_CURSOR_LINE_HORI            111
#define IDD_DIALOG_DISPLAY_OPTIONS      113
#define IDD_DIALOG_NEW_GAME             115
#define IDD_DIALOG_END_GAME             117
#define IDD_DIALOG_SELECT_PLAYER        119
#define IDD_DIALOG_EDIT_PLAYER          121
#define IDD_DIALOG_REMOVE_PLAYER        123
#define IDD_DIALOG_REVIEW_PLAYERS       125
#define IDC_DO_EDIT_SIZING              1000
#define ID_QUIT                         1000
#define IDC_AP_BTN_PCOL                 1001
#define IDC_EG_BTN_REPLAY               1001
#define IDC_AP_EDIT_BLUE                1002
#define IDC_DO_CHKBX_FILL               1002
#define IDC_EG_STC_PLACINGS             1002
#define IDC_EP_BTN_EDIT                 1002
#define IDC_AP_EDIT_GREEN               1003
#define IDC_NG_TIMED_GAME               1003
#define IDC_AP_EDIT_RED                 1004
#define IDC_DO_BTN_BACK_CHOOSE          1004
#define IDC_EP_STC_WINS                 1004
#define IDC_NG_EDIT_MINUTES             1004
#define IDC_RP_BTN_REMOVE               1004
#define IDC_AP_RAD_SCHEME               1005
#define IDC_EP_STC_LOSSES               1005
#define IDC_NG_EDIT_SECONDS             1005
#define IDC_RP_STC_SELECTED             1005
#define IDC_EP_STC_DRAWS                1006
#define IDC_RP_LIST_PLAYERS             1006
#define IDC_VP_LST_PLAYERS              1006
#define IDC_VP_STC_NAME                 1007
#define IDC_EP_BTN_COLOUR               1008
#define IDC_VP_STC_WINS                 1008
#define IDC_VP_STC_DRAWS                1009
#define IDC_AP_RAD_HUMAN                1010
#define IDC_VP_STC_LOSSES               1010
#define IDC_EP_STC_NAME                 1011
#define ID_AP_RAD_DUMB                  1011
#define IDC_AP_RAD_MED                  1012
#define IDC_EP_LST_PLAYERS              1012
#define IDC_AP_RAD_SMART                1013
#define IDM_NEW_GAME                    40000
#define IDM_SAVE_PLAYERS                40001
#define IDM_ADD_PLAYER                  40002
#define IDM_EXIT                        40003
#define IDM_INDEX                       40004
#define IDM_ABOUT                       40005
#define IDM_REMOVE_PLAYER               40006
#define IDM_PLAYER_OPTIONS              40007
#define IDM_DISPLAY_OPTIONS             40008
#define IDM_REVIEW_PLAYERS              40009
#define IDM_START                       40010
#define IDC_DO_EDIT_SPACING             40014
#define IDC_DO_EDIT_DRAW_RED            40021
#define IDC_DO_EDIT_DRAW_GREEN          40022
#define IDC_DO_EDIT_DRAW_BLUE           40023
#define IDC_DO_EDIT_BACK_RED            40024
#define IDC_DO_EDIT_BACK_GREEN          40025
#define IDC_AP_EDIT_NAME                40026
#define IDC_DO_EDIT_BACK_BLUE           40026
#define IDC_AP_BTN_EXIST                40027
#define IDC_NG_EDIT_SIZE_X              40029
#define IDC_NG_EDIT_SIZE_Y              40030
#define IDC_NG_BTN_DSPOPT               40031
#define IDC_DO_EDIT_DOT_RED             40035
#define IDC_DO_EDIT_DOT_GREEN           40036
#define IDC_DO_EDIT_DOT_BLUE            40037
#define IDC_DO_BTN_DOT_CHOOSE           40038
#define IDC_DO_BTN_DISP_CHOOSE          40039
#define IDC_EP_EDIT_RED                 40042
#define IDC_EP_EDIT_GREEN               40043
#define IDC_EP_EDIT_BLUE                40044
#define IDC_EP_EDIT_NAME                40045
